# Generated by Django 6.0.2 on 2026-03-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
